export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const GET_QUANTITY_USERS_REQUEST = 'GET_QUANTITY_USERS_REQUEST'
export const GET_QUANTITY_USERS_SUCCESS = 'GET_QUANTITY_USERS_SUCCESS'
export const GET_QUANTITY_USERS_ERROR = 'GET_QUANTITY_USERS_ERROR'